---
abstract: 'A general-purpose sensitivity analysis tool for user-supplied calculations and parameters'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simulation-Sensitivity
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Simulation::Sensitivity:
    file: lib/Simulation/Sensitivity.pm
    version: 0.12
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Params::Validate: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/Simulation-Sensitivity/issues
  homepage: https://github.com/dagolden/Simulation-Sensitivity
  repository: https://github.com/dagolden/Simulation-Sensitivity.git
version: 0.12
x_authority: cpan:DAGOLDEN
